### ISSUE TITLE
Chrome does't allow to use this extension

### ISSUE THREAD

**Issue by giorgi1517** [xxzefgh/youtube-classic-extension#10]
Downloaded .crx file, installed it, but can't turn extension on
![image](https://user-images.githubusercontent.com/6876423/50918429-a4245480-1459-11e9-9393-488e0470a9d2.png)

**Comment by xxzefgh** [comment]
![load_chrome_extension](https://user-images.githubusercontent.com/6980903/50997333-b677be80-153d-11e9-9bf8-29b4e612733e.gif)
