### ISSUE TITLE
Regression: Youtube doesn't open in "Classic Mode" on first try when using a private window

### ISSUE THREAD

**Issue by spodermenpls** [xxzefgh/youtube-classic-extension#14]
As described in the title, the new version 1.4 requires a reload when Youtube gets opened in a new private window, to switch from the slow, "modern" UI to the fast, "old" UI. I am using Firefox 67.0.1 (64 bit) on Windows 10. When reverting back to Youtube Classic 1.3, Youtube opens immediately and reliably in the "Classic Theme", without a reload.

**Comment by xxzefgh** [comment]
thanks, 1.4.1 released with a fix.

**Comment by spodermenpls** [comment]
Thanks, now it's working like before again.

On that note, there's another weird "reload issue" with the menu (at least on my system), where it displays "Enable" and "Home page" only on every second try:
![menu](https://user-images.githubusercontent.com/23747593/59250713-55593180-8c28-11e9-890e-10512e061657.JPG) 
![menu2](https://user-images.githubusercontent.com/23747593/59250755-76218700-8c28-11e9-9893-15ddc5933322.JPG)
