### ISSUE TITLE
Comments blocking

### ISSUE THREAD

**Issue by Hueristic** [xxzefgh/youtube-classic-extension#16]
Apparently with this plugin installed comments will not load. Fix if possible please, the patch worked great on load time. :)

F.F 69.0

**Comment by Marek33** [comment]
I have seen this issue as well, but since reloading the page fixes it, I don't have a problem with that. However, it would be nice to see it fixed.

**Comment by Hueristic** [comment]
I attempted refresh multiple times before disabling extension. I also allowed a few domains (google tracking) that i normally block without issue to no avail. So possibly this has changed again since you checked?

Could you try again?

**Comment by Marek33** [comment]
That's weird, since it still works for me. Maybe only the Chrome version has that issue, but since it's not in the store, I've not used it yet.

I did it on Firefox and Waterfox, but it works without any issues. However, did you try to look first at the comments than the video? That works for me every time.

**Comment by Hueristic** [comment]
That worked. :)

    On Wednesday, October 2, 2019, 7:19:45 AM EDT, Marek33 <notifications@github.com> wrote:  
 
 
That's weird, since it still works for me. Maybe only the Chrome version has that issue, but since it's not in the store, I've not used it yet.

I did it on Firefox and Waterfox, but it works without any issues. However, did you try to look first at the comments than the video? That works for me every time.

**Comment by Marek33** [comment]
That's good to hear, and I hope it will be fixed eventually.

**Comment by Hueristic** [comment]
Yup, when google stops trying to push everyone to chrome. :)
IOW, when pigs fly ;D

    On Thursday, October 3, 2019, 4:23:24 PM EDT, Marek33 <notifications@github.com> wrote:  
 
 
That's good to hear, and I hope it will be fixed eventually.

**Comment by Marek33** [comment]
With the ManifestV3 restrictions, I think that most of the people, who use extensions, will eventually move from the Chrome, but unfortunately, it's less than 40% (Firefox, not sure about Chrome) from what I read some time ago.

**Comment by seascape** [comment]
I just ended up here because YT comments have stopped loading in my main Firefox browser, and I've found it's due to YouTube Classic.

Curiously, comments still load in my other Firefox with this add-on running. (I use portable versions on Windows 10.)

**Comment by xxzefgh** [comment]
I know this is an issue and sometimes also happens to me, but I can't do anything about it.
