### ISSUE TITLE
This version of YouTube is going away soon

### ISSUE THREAD

**Issue by Marek33** [xxzefgh/youtube-classic-extension#18]
A few days ago, I noticed a blue bar on the YouTube, which said: This version of YouTube is going away soon. Switch to the new YouTube. So, I would like to know what it means for your extension, and what will happen, if they will remove the old layout. I have only noticed it, when I was signed in, so at least normally, it doesn't show up.

There is a Reddit thread about it: https://old.reddit.com/r/youtube/comments/ellkt4/misc_fd_rip_old_layout/ and one person, ask about it, on the Google support, but that person hasn't got a response yet: https://support.google.com/youtube/thread/24987355?hl=en

**Comment by xxzefgh** [comment]
I am skeptical that they will remove support for older browsers, but if they do, I might put an effort into restyling new layout to match old one.

**Comment by Marek33** [comment]
I hope that they don't do that, but most of the software, which I have the latest updates.

Is it possible to have most of the layout be just like the old one, if they decide to remove it? Since, the newer one, is much slower, even on high end machines.

**Comment by xxzefgh** [comment]
So, I've changed user agent and looks like they really are removing support for older browsers. Well, fuck'em
![image](https://user-images.githubusercontent.com/6980903/73718008-c22fb780-4734-11ea-871f-b413a8e3f646.png)

**Comment by xxzefgh** [comment]
btw, if you want to remove alert, use custom theme in Enhancer for YouTube
```css
#old-browser-alert {
  display: none;
}
```

**Comment by hong620** [comment]
seems they start to announce the message region by region.
(3 weeks halt for announce webpage translation)

even microsoft wasn't complain about Youtube's shadow DOM API issue and now they're using Chromium engine for they're new Edge browser.

not a suprised so.. i'm start to little worried about how much slows they're new design in Firefox Specific. 😖

**Comment by RafalRambo** [comment]
> 
> 
> btw, if you want to remove alert, use custom theme in Enhancer for YouTube
> 
> ```css
> #old-browser-alert {
>   display: none;
> }
> ```

Hi. I use theme Red Dark in Enhancer for YouTube and this script not working. 
Is there a script that works with this theme?

**Comment by gioxx** [comment]
If you use Adblock you can add this filter:
`youtube.com##.alerts-wrapper`

**Comment by RafalRambo** [comment]
@gioxx 
Thx. It works.

**Comment by Marek33** [comment]
@xxzefgh I don't mind that, but, I'm afraid, that when they remove that layout, it will not be possible to have it, like it is now. And why would you be using an old browser anyway?

Also, do you know why this excellent extension, was removed from the Chrome Store? I have seen threads about it, but I have never seen any answer to that.

**Comment by xxzefgh** [comment]
@Marek33 to be honest, I didn't notice any performance issues, I just wanted old layout and that's why I made this. restyling would be enough for me.
and as for the chrome store, I don't know what policies were violated. this is what they sent me
![Screenshot_20200205-080346_Gmail](https://user-images.githubusercontent.com/6980903/73809915-25315500-47ee-11ea-9f0a-e3c9d9ec8837.jpg)

**Comment by xxzefgh** [comment]
btw M$ approved it so anyone can use it on edge

https://microsoftedge.microsoft.com/addons/detail/icocefkkfkmmiclcobgcnpnjdmmpgdna

**Comment by Marek33** [comment]
@xxzefgh I did notice quite a slower loading, and also the website performance tests, like the gtmetrix have proven me, right by that.

That's quite a weird explanation, from their side, but since they did not want to allow some newer versions of the uBlock Origin there, it makes sense that they wouldn't even care for smaller extensions.

I don't think that Edge will have any privacy oriented Forks, so it's not much for me. Ungoogled and Iridium at least, doesn't ask me all the time to stop using the developer mode, like the Brave.

**Comment by refriedfood** [comment]
As of 04/22/2020 this plugin seems to be obsolete on firefox.

**Comment by Marek33** [comment]
@refriedfood  I had had some issues in the last week, with having a new layout as well, but it's very easy to fix. Just clean the history and open the YouTube again. Though, it did happen only on the Chromium, and not on Firefox.

**Comment by refriedfood** [comment]
@Marek33 My settings erase my history and cache/cookies, etc every time I close the browser. It just doesn't seem to work any longer for me (FF v62/p).

**Comment by Marek33** [comment]
@refriedfood  You should update it since its quite an old version, and try a newer one. Maybe then, it will be fixed, since I had almost no problems with it.

**Comment by xxzefgh** [comment]
make sure you update the extension to 1.5.1

**Comment by Marek33** [comment]
@xxzefgh  Will you release the 1.5.1 to Github as well? I would prefer to download it, from here than from the Chrome Web Store.

**Comment by xxzefgh** [comment]
@Marek33 yes I just did that.

**Comment by Marek33** [comment]
@xxzefgh Thanks!

Also, have you removed that blue bar, which I mentioned in the title name? Since, now, when I visit YouTube, with uBlockOrigin and uMatrix, turned off, I no longer have it?

**Comment by refriedfood** [comment]
@xxzefgh 151 isn't offered on the addons site for me(?). Still 1.4.1. no xpi anywhere.

**Comment by Marek33** [comment]
Yes, it seems there is only the one for Chrome. Thought, in the add-on store, there is a newer version, but I would still prefer to have a download for it here.

**Comment by xxzefgh** [comment]
I don't know why you can't update. Use "Check for update" button on addons manager page to force updates.

**Comment by refriedfood** [comment]
Literally, as you posted that, I was able to magically get it through firefox instead of their addon site and now it's 1.5.1 and working again. Thanks.

**Comment by maxw2000** [comment]
The YouTube Studio Legacy button is gone now, Creators are now forced to use the ugly new theme.
Is there any chance of adding the old theme for YouTube Studio back in?

Thank you!

**Comment by xxzefgh** [comment]
Hello, unfortunately not.

**Comment by krystian3w** [comment]
> 
> 
> > btw, if you want to remove alert, use custom theme in Enhancer for YouTube
> > ```css
> > #old-browser-alert {
> >   display: none;
> > }
> > ```
> 
> Hi. I use theme Red Dark in Enhancer for YouTube and this script not working.
> Is there a script that works with this theme?

ate `!important;` when should works without uBO/AG/ABP/AdBlock.

**Comment by Marek33** [comment]
@krystian3w Thanks, but I did remove it back in January. Though, I'm afraid, that if they completely remove the layout, then there will be no extension, which will be able to bring back the old one.

**Comment by Nicholas-Steel** [comment]
> 
> 
> @xxzefgh Thanks!
> 
> Also, have you removed that blue bar, which I mentioned in the title name? Since, now, when I visit YouTube, with uBlockOrigin and uMatrix, turned off, I no longer have it?

I too no longer have it appear and I've disabled my adblocker and Enhanced Tracking Protection to confirm they aren't causing its eradication.

**Comment by Marek33** [comment]
@Nicholas-Steel  I would recommend you to use the uBlock Origin, since classic ad blockers, aren't that great, and most of them already sold out. Please, make sure, when you search for the _uBlock_, to use the **uBlock Origin**, and not the classic uBlock, since that is a stolen project, and it's not recommended.

Also, since it seems that it's really gone, I will close this.

**Comment by Nicholas-Steel** [comment]
I already use uBlock Origin, I use adblocker as a catch-all term.

**Comment by Marek33** [comment]
I understand, and that's good to know!
