### ISSUE TITLE
Doesn't work with the latest Chrome/Ungoogled.

### ISSUE THREAD

**Issue by Marek33** [xxzefgh/youtube-classic-extension#19]
A couple of days ago Ungoogled has released a newer version of its Chrome fork, and unfortunately, the YouTube Classic no longer works. I tried it, with the latest Chrome as well, to be sure, that there isn't a problem with Ungoogled not being supported, but it also doesn't work on that as well.

I can install the extension, but the YouTube has still a new layout.

**Comment by Marek33** [comment]
@xxzefgh I hope you are not busy with the coronavirus, but if you aren't, I hope that you can fix the situation, meanwhile, when there is a quarantine, since one never knows, when they could remove the design.

**Comment by xxzefgh** [comment]
hey, I just tried with chrome 80 and it works. can you tell me what version do you have?

**Comment by Marek33** [comment]
Thanks! I was using the 1.2 and now I'm using the 1.4.2, which works.

However, why are the icons different from the 1.2? It's certainly not an issue, since I can change it, but I do wonder why.
