### ISSUE TITLE
Missing video tumbnails

### ISSUE THREAD

**Issue by inkybet** [xxzefgh/youtube-classic-extension#20]
![image](https://user-images.githubusercontent.com/62082231/76475029-818f2200-63f5-11ea-818b-c1b8ba2cb84c.png)
![image](https://user-images.githubusercontent.com/62082231/76475072-b26f5700-63f5-11ea-87d6-d4d8015015b6.png)

Since the end of February video thumbnails aren't loading properly on the home page or search pages. 
I've been using this add on on Firefox since early Feb and it was working fine at the beginning, even with all other add ons disabled the problem remains.
I just wished to bring this to your attention as others have left reviews on Firefox site but not detailing the problem. Thank you for your time and effort.

**Comment by fakeid30** [comment]
@inkybet why was this issue closed?

**Comment by inkybet** [comment]
the issue has disappered


________________________________
