### ISSUE TITLE
The extension can't be installed globally because it's missing an add-on ID

### ISSUE THREAD

**Issue by cameel** [xxzefgh/youtube-classic-extension#21]
Please add a unique ID in the `manifest.json`. It's optional in most cases but one thing you cannot do without it is to put the XPI in the global `/usr/lib/firefox/browser/extensions/` directory and have the add-on available automatically in all profiles.

Theoretically all add-ons have an ID since a temporary one is assigned by AMO when an add-on is signed and `about:debugging` shows that it's `{6acd0f4d-ab79-4b79-9b28-8bde65ae355c}` for this extension but unfortunately Firefox still does not see the extension if I try to use it. Looks like one in `manifest.json` is necessary.

References:
- [Extensions and the add-on ID](https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/)
- [Sideloading add-ons > Installation using the standard extension folders](https://extensionworkshop.com/documentation/publish/distribute-sideloading/#standard-extension-folders)

**Comment by xxzefgh** [comment]
Would this be enough? https://github.com/xxzefgh/youtube-classic-extension/commit/5b08be15a5c36a3585debda4779a980f7aa6caca

**Comment by cameel** [comment]
Yeah, this should do the trick. That's what other extensions do.

Unfortunately I can't test it in a meaningful way without this being signed but I'll report if it works once this gets released.

**Comment by xxzefgh** [comment]
1.5.2 has been released

**Comment by cameel** [comment]
I just tested it and it works as expected. Thanks!
