### ISSUE TITLE
Video description box can't be expanded

### ISSUE THREAD

**Issue by larmax** [xxzefgh/youtube-classic-extension#25]
Seems to be broken by google on purpose, so it might not be possible to fix. The full description is still in the source though...

**Comment by ShinyaOsen** [comment]
changing language can get it back

**Comment by Hammer7IL** [comment]
Changing language to what? Just tried it and there is still no "show more" button.

**Comment by ShinyaOsen** [comment]
I had the best luck with asian languages but now I can only get it back when I switch accounts and thats only like 50% of the time

**Comment by Nicholas-Steel** [comment]
I can confirm the box is missing and so is the "Share" button.

**Comment by Scias90** [comment]
Same. It's been broken for me for the last week or so.

**Comment by jackysee** [comment]
I wrote a userscript to add the toggle button here https://gist.github.com/jackysee/ea4d247515147e36d44d3bee661d4928

**Comment by sliperhr** [comment]
> I wrote a userscript to add the toggle button here https://gist.github.com/jackysee/ea4d247515147e36d44d3bee661d4928

not working

**Comment by Nicholas-Steel** [comment]
The "Old Youtube" extension seems to expand the description box.
