### ISSUE TITLE
It stopped working on firefox

### ISSUE THREAD

**Issue by snoopdoggtg** [xxzefgh/youtube-classic-extension#29]
It just stopped working, reinstalling, restarting, etc. doesn't help

**Comment by AccountMadeJustForThis** [comment]
I literally just made an account to post about this, also my "show more" and "share" buttons disappeared before this too. Is this just Google trying to get rid of plugins like this or does this need to be updated?

**Comment by LothaireCliquennois** [comment]
Same issue 🗡️

**Comment by Scias90** [comment]
Yep, same here. Hopefully there will be an update that fixes this because the new layout is garbage. Also, before it broke, "show more" button broke beforehand.

**Comment by RussEfarmer** [comment]
Can confirm, new YouTube is annoying :(

**Comment by Wishbringer** [comment]
New layout actually crashes my tab in Subscriptions section, need solution.

**Comment by Nicholas-Steel** [comment]
Don't blame this extension, blame Youtube/Google. The company did warn us the old design was going away at some point. If you thought Classic-Youtube was somehow recreating the classic Youtube experience, that's a wrong assumption, it was merely fooling the Youtube server in to delivering the old design to your browser.

**Comment by ReimuHakurei** [comment]
I installed this addon:

https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/

And overrode my user-agent for *.youtube.com to that of Pale Moon (which is based on an ancient version of Firefox) as such: 

> Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:25.8) Gecko/20151126 Firefox/31.9 PaleMoon/25.8.1

Works now.

**Comment by o5k** [comment]
Setting the User-Agent to any version of FF of 43 or below seems to work for now, albeit displaying a banner:

![](https://kagari.moe/:/2020-06-15_21-29-42.png)

On Firefox versions under 71, this can be accomplished easily with about:config flag `general.useragent.override.youtube.com=Mozilla/5.0 (Windows NT 6.1; Win64; rv:43.0) Gecko/20100101 Firefox/43.0`

Can't wait for Google to force the 5x slower Polymer down the throats of those who need XUL/XPCOM extensions :)))))))

**Comment by Charlie5Lives** [comment]
It stopped working on Chrome as well.

**Comment by spodermenpls** [comment]
@ReimuHakurei @o5k Thanks for the UAS spoofing tip. That workaround works on my end only while being logged-out, though, while being logged-in it still displays the new Layout. Do you have the same problem, or is there a workaround for this too?

**Comment by ReimuHakurei** [comment]
It works when logged for me, so not sure.

**Comment by bottlehead** [comment]
With the spoofing extension and Youtube Classic extension activated it still displays the new layout and it crashes all the time, too. Super annoying.
Now comes the really strange thing.
Without any Youtube Classic/UAS spoof I can switch into another channel on the same email and it will show me the old layout again. How does this happen?

main account with new layout: http://puu.sh/FWPhC/2d397606fc.jpg
alt account with old layout: http://puu.sh/FWPim/29356f7dc4.jpg

So if you don't mind not having your playlists available, try switching to another channel if you got multiple.

**Comment by hejops** [comment]
This can be fixed (for now) by doing the following:

1. Enable cookies on YouTube (if you don't already)
2. Open Developer Tools (F12)
3. Go to Storage > Cookies
4. Look for the PREF setting and add "&f6=8"

I suspect this functionality will eventually be removed though.

**Comment by bottlehead** [comment]
@hejops this also does not work for me, i'm on Firefox 66.

**Comment by xxzefgh** [comment]
Hello, it has been updated to 1.5.4, but it's time to let it go at this point. Old layout will be gone soon.

**Comment by LothaireCliquennois** [comment]
![image](https://user-images.githubusercontent.com/41753021/84762006-c5c42c80-afb9-11ea-964f-f33071d36560.png)

**Comment by LothaireCliquennois** [comment]
Basically, it means that the module seems to be corrupted.

**Comment by Morku** [comment]
@xxzefgh 
Thank you for the effort and great Add-On over time.
Unfortunately the update it only works when I use Youtube without Account.
As soon I Log-In, I get the new Layout.

So I tried Internet Explorer which loads the old Layout by default. As soon I Log-In, I get the New Layout which is not even made for IE.
Like they store now the information in Account that the user is capable to use the New Layout.
Nothing we can do I think :(

**Comment by spodermenpls** [comment]
The issues while being logged-in only occur with my primary channel, with my other ones the old layout persists also while logged-in. Spoofing the UAS unfortunately deactivates the Chat box (Live + replay) and search recommendations underneath the search bar.

**Comment by Marek33** [comment]
@xxzefgh The latest update has fixed it for me, so thanks for the fix!

However, why you want to let it go? The YouTube has switched to this layout more than 2 years ago, and since we know, how bad YouTube are at these things, maybe it will be another six months, until they remove it completely.

Also, please release the fix for the Chromium browsers as well, since there I still have the new layout, and I mostly use Ungoogled/Iridium for the YouTube.

**Comment by bottlehead** [comment]
> 
> 
> @xxzefgh
> Thank you for the effort and great Add-On over time.
> Unfortunately the update only works when I use Youtube without Account.
> As soon I Log-In, I get the new Layout.
> 
> So I tried Internet Explorer which loads the old Layout by default. As soon I Log-In, I get the New Layout which is not even made for IE.
> Like they store now the information in Account that the user is capable to use the New Layout.
> Nothing we can do I think :(
> 
> (Firefox 77.0.1 x64, Windows 10 x64 2004)

It also doesn't work for me and I thought they might put a cookie or something in your account that forces the new layout if you had it once.

**Comment by Nicholas-Steel** [comment]
For everyone having bizarre issues, try clearing your cookies for Youtube and updating your Youtube Classic add-on.
