### ISSUE TITLE
UI does not go to classic mode.

### ISSUE THREAD

**Issue by Nuclearfarts** [xxzefgh/youtube-classic-extension#34]
This appears to be caused by yesterday's change of switching back to cookies -- perhaps Youtube no longer respects that cookie?

**Comment by gottabeleGIT** [comment]
Same issue here on both Safari and Firefox, there was a banner that said the classic interface was going away soon, maybe they finally killed it...

**Comment by OothecaPickle** [comment]
using a chrome 53.0.2785.143 or earlier user agent works for me.

**Comment by LothaireCliquennois** [comment]
Neither does it for me, the app is still kind of bugged out I guess.

**Comment by gottabeleGIT** [comment]
@OothecaPickle Just tried that, and it seems to load the classic interface but thumbnails appear blank and there is now a yellow banner at the top of the page that says “We’ll stop supporting this browser soon.”

**Comment by Nuclearfarts** [comment]
?disable_polymer=1 still works for me.

**Comment by gottabeleGIT** [comment]
Tried it both ways with no success on my end unfortunately, the user agent workaround should be fine for now though...

**Comment by motfis** [comment]
> 
> 
> ?disable_polymer=1 still works for me -- remember that you need it to be &disable_polymer=1 since most videos pages already have a GET parameter.

&disable_polymer=1 --> confirm to work. @xxzefgh could you update it like prev version with &?

**Comment by LothaireCliquennois** [comment]
The disable polymer add to the link still shows me the old interface :D
Maybe I should erase all cookies, that'll probably help a bit

**Comment by danielocdh** [comment]
I usually just use a cookie setting but today it seems youtube finally removed the old interface.
I assumed extensions were actually changing the css in preparation for the removal but I can't find any extension that actually did that.
Now that the removal happened, it might be really hard to do it the right way as I don't think there is a way to actually load the old site to be able to reproduce it.

**Comment by OothecaPickle** [comment]
a firefox 43.0.4 or earlier user agent also enables the old interface

**Comment by evgius** [comment]
old tabs works. new - no, i don't know how this can be connected. please god of github and oldgoodYT we pray you help us!!

**Comment by Nicholas-Steel** [comment]
NuclearFarts has the solution, just need a way to automate it. For some web pages (Videos list on a channel) **?disable_polymer=1** works correct and for others (viewing an actual video)  **&disable_polymer=1** is needed instead.

**Comment by ghost** [comment]
@OothecaPickle that seems to work too

**Comment by sergeevabc** [comment]
Just remove this and install working [Old Youtube][1] extension.

![](https://i1.imageban.ru/out/2020/06/20/4deef73a359b7802beb9ab1b30239a71.webp) ![](https://i3.imageban.ru/out/2020/06/20/2d3ae8c86a1bafdf1af0477a8652ca4b.webp)

[1]: https://addons.mozilla.org/en-US/firefox/addon/old-youtube/

**Comment by AccountMadeJustForThis** [comment]
Thank you @sergeevabc
