### ISSUE TITLE
"Show more" in video decription

### ISSUE THREAD

**Issue by elektraking** [xxzefgh/youtube-classic-extension#35]
I have noticed that if there is a longer text in the description under a video, usually there is supposed to be "show more" which we click on to see all the notes. However, now with "Restore Classic YouTube!" enabled the link is not present and we can see only the first three rows.

**Comment by xxzefgh** [comment]
If you looked a little bit more, you would've noticed that there were issues opened for that, and the answer is - I can do nothing.
thank you.
